# site setting
title: eight
baseurl: http://eight.hatkit.com
favicon: favicon.png
tagline: Sample Optin Form
banner-image: home-banner1.jpg
exclude: ['README.md']
permalink: pretty #to remove .html
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

#Gems
gems: [jekyll-paginate]
paginate: 60
paginate_path: "/blog/page:num/"
  
include: ['_pages']

